-- AURA wellbeing support data. Private journal content is never exposed to support people by default.
create table if not exists aura_profiles (user_id uuid primary key references auth.users on delete cascade, name text not null default 'Alex', timezone text not null default 'UTC', communication_style text not null default 'standard', encouragement_style text not null default 'warm', reduced_motion boolean not null default false, gamification_enabled boolean not null default false, low_demand_preferences jsonb not null default '{}');
create table if not exists aura_routines (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, name text not null, time_period text not null check(time_period in ('morning','afternoon','evening')), active boolean not null default true, days_of_week int[] not null default '{1,2,3,4,5,6,0}', created_at timestamptz not null default now());
create table if not exists aura_routine_items (id uuid primary key default gen_random_uuid(), routine_id uuid not null references aura_routines on delete cascade, title text not null, description text, scheduled_time time, estimated_minutes int check(estimated_minutes > 0), sort_order int not null default 0, optional boolean not null default false, minimum_version text);
create table if not exists aura_task_steps (id uuid primary key default gen_random_uuid(), routine_item_id uuid not null references aura_routine_items on delete cascade, title text not null, sort_order int not null default 0, complete boolean not null default false);
create table if not exists aura_daily_task_status (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, routine_item_id uuid references aura_routine_items on delete cascade, day date not null default current_date, status text not null check(status in ('todo','started','complete','skipped','rescheduled')), unique(user_id,routine_item_id,day));
create table if not exists aura_check_ins (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, energy text not null, sensory_load text not null, social_capacity text, created_at timestamptz not null default now());
create table if not exists aura_values (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, name text not null);
create table if not exists aura_values_actions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, value_id uuid references aura_values on delete cascade, action text not null, created_at timestamptz not null default now());
create table if not exists aura_reflections (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users on delete cascade, kind text not null, content jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists aura_settings (user_id uuid primary key references auth.users on delete cascade, settings jsonb not null default '{}');
do $$ declare t text; begin foreach t in array array['aura_profiles','aura_routines','aura_routine_items','aura_task_steps','aura_daily_task_status','aura_check_ins','aura_values','aura_values_actions','aura_reflections','aura_settings'] loop execute format('alter table %I enable row level security',t); end loop; end $$;
create policy aura_profiles_owner on aura_profiles for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy aura_routines_owner on aura_routines for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy aura_items_owner on aura_routine_items for all using(exists(select 1 from aura_routines r where r.id=routine_id and r.user_id=auth.uid())) with check(exists(select 1 from aura_routines r where r.id=routine_id and r.user_id=auth.uid()));
create policy aura_steps_owner on aura_task_steps for all using(exists(select 1 from aura_routine_items i join aura_routines r on r.id=i.routine_id where i.id=routine_item_id and r.user_id=auth.uid())) with check(exists(select 1 from aura_routine_items i join aura_routines r on r.id=i.routine_id where i.id=routine_item_id and r.user_id=auth.uid()));
do $$ declare t text; begin foreach t in array array['aura_daily_task_status','aura_check_ins','aura_values','aura_values_actions','aura_reflections'] loop execute format('create policy %I on %I for all using(user_id=auth.uid()) with check(user_id=auth.uid())',t||'_owner',t); end loop; end $$;
create policy aura_settings_owner on aura_settings for all using(user_id=auth.uid()) with check(user_id=auth.uid());
